### ISSUE TITLE
Hardcoded file path in DomainSettingsModel.Cs

### ISSUE THREAD

**Issue by caz3542** [ArmandJ77/CQRSAndMediator-Scaffolding#2]
The solution fails to run when due to a hardcoded file path the DomainSettingsModel.cs file

**Comment by ArmandJ77** [comment]
Greetings,

Thank you for bringing this to my attention, I believe the bug has been resolved in v1.1.2 of the package. 🎉

**Comment by caz3542** [comment]
Dankie.
